# Desabilita o SSD1306 padrão (será configurado pelo shield específico)
CONFIG_SSD1306=n

# Configurações para RGB
CONFIG_SPI=y
CONFIG_SPI_NRFX_SPIM3=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
